(()=>{
const KEY='air_profile_memory';
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){return null}};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const avg=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0;
function slope(values){const n=values.length;if(n<2)return 0;const mx=(n-1)/2,my=avg(values);let num=0,den=0;for(let i=0;i<n;i++){const dx=i-mx;num+=dx*(values[i]-my);den+=dx*dx}return den?num/den:0}
function snapshot(){const memory=read(),entries=(memory?.entries||[]).filter(e=>Number.isFinite(Number(e.health))&&Number.isFinite(Number(e.ratio))).slice(-6);const n=entries.length;if(!n)return{status:'EMPTY',sessions:0,score:0,ratioSlope:0,healthSlope:0,offset:0};const ratios=entries.map(e=>Number(e.ratio)||1),health=entries.map(e=>clamp(Number(e.health)||0,0,1)),ratioSlope=slope(ratios),healthSlope=slope(health),recent=ratios.slice(-Math.min(3,n)),offset=avg(recent.map(v=>Math.abs(v-1))),recentHealth=avg(health.slice(-Math.min(3,n)));let status='LEARNING';if(n>=3){const last2=ratios.slice(-2),persistentShift=last2.length===2&&last2.every(v=>Math.abs(v-1)>=.22);if(persistentShift||offset>=.25||recentHealth<.52)status='SHIFTED';else if(Math.abs(ratioSlope)>=.045||healthSlope<=-.065||offset>=.14||recentHealth<.66)status='DRIFTING';else status='CENTERED'}const centerScore=1-clamp(offset/.28,0,1),trendScore=1-clamp(Math.abs(ratioSlope)/.08,0,1),healthScore=clamp(recentHealth,0,1),score=clamp(centerScore*.4+trendScore*.3+healthScore*.3,0,1);return{status,sessions:n,score,ratioSlope,healthSlope,offset,recentHealth}}
const el=document.querySelector('#memoryTrend');
function render(){if(!el)return;const s=snapshot();el.dataset.drift=s.status;const pc=Math.round(s.score*100);if(s.status==='EMPTY'){el.textContent='DRIFT · NESSUN DATO';el.title='Nessuna sessione validata disponibile.';return}if(s.status==='LEARNING'){el.textContent=`DRIFT · LEARNING ${s.sessions}/3`;el.title='Servono almeno tre sessioni validate per stimare una deriva.';return}const labels={CENTERED:'CENTRATO',DRIFTING:'IN OSSERVAZIONE',SHIFTED:'SPOSTATO'};el.textContent=`DRIFT · ${labels[s.status]} · ${pc}%`;el.title=`Offset ${s.offset.toFixed(3)} · trend scala ${s.ratioSlope>=0?'+':''}${s.ratioSlope.toFixed(3)}/sessione · trend qualità ${s.healthSlope>=0?'+':''}${s.healthSlope.toFixed(3)}/sessione`}
render();setInterval(render,2400);window.addEventListener('storage',e=>{if(e.key===KEY)render()});window.AirDriftMonitor={snapshot,render};
})();