window.AirGestureEngine=class{
constructor(o={}){
this.profiles={
precise:{smooth:.18,pinchIn:.045,pinchOut:.078,pinchHold:320,swipeDistance:.32,swipeWindow:300,palmHold:2100,fistHold:2800,restHold:550,scrollArm:420,scrollStep:.022,cooldown:850,poseStill:.008},
balanced:{smooth:.24,pinchIn:.050,pinchOut:.083,pinchHold:280,swipeDistance:.30,swipeWindow:290,palmHold:1900,fistHold:2500,restHold:480,scrollArm:360,scrollStep:.020,cooldown:760,poseStill:.010},
fast:{smooth:.30,pinchIn:.055,pinchOut:.090,pinchHold:240,swipeDistance:.27,swipeWindow:270,palmHold:1650,fistHold:2200,restHold:420,scrollArm:320,scrollStep:.018,cooldown:680,poseStill:.012}
};
this.profile=o.profile||'balanced';this.o={...this.profiles[this.profile],safetyGap:650,...o};this.adaptiveScale=o.adaptiveScale!==false;this.refScale=.18;this.handScale=this.refScale;this.scaleFactor=1;this.sx=.5;this.sy=.5;this.hist=[];this.pinch=false;this.pinchAt=0;this.palmAt=0;this.fistAt=0;this.palmArmed=true;this.fistArmed=true;this.last=0;this.listeners={};this.intent={type:null,confidence:0};this.poseMotion=0;this.lastPalmCenter=null;this.commandReady=false;this.restAt=0;this.poseName='neutral';this.scrollAt=0;this.scrollActive=false;this.scrollLastY=null;this.scrollLastFire=0;this.stats={frames:0,gestures:0,pinch:0,swipe:0,palm:0,scroll:0,fist:0,intents:0};
}
on(n,f){(this.listeners[n]??=[]).push(f);return this}
emit(n,d={}){(this.listeners[n]||[]).forEach(f=>f(d))}
setProfile(name){if(!this.profiles[name])return false;this.profile=name;Object.assign(this.o,this.profiles[name]);this.emit('profile',{name,options:{...this.o}});return true}
setAdaptiveScale(enabled){this.adaptiveScale=!!enabled;this.emit('adaptive',{enabled:this.adaptiveScale});return this.adaptiveScale}
dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
clamp(v,a,b){return Math.max(a,Math.min(b,v))}
palmCenter(l){const ids=[0,5,9,13,17];return{x:ids.reduce((s,i)=>s+l[i].x,0)/ids.length,y:ids.reduce((s,i)=>s+l[i].y,0)/ids.length}}
updatePoseMotion(l){const c=this.palmCenter(l);if(this.lastPalmCenter){const d=Math.hypot(c.x-this.lastPalmCenter.x,c.y-this.lastPalmCenter.y);this.poseMotion=this.poseMotion*.76+d*.24}this.lastPalmCenter=c;return this.poseMotion}
extended(l,t,p,r=1.2){return this.dist(l[t],l[0])>this.dist(l[p],l[0])*r}
curled(l,t,p,r=.92){return this.dist(l[t],l[0])<this.dist(l[p],l[0])*r}
isPalm(l){const scale=Math.max(.04,this.handScale),tips=[8,12,16,20],pips=[6,10,14,18];const ext=tips.map((t,i)=>this.extended(l,t,pips[i],1.30));const spread=this.dist(l[8],l[20])>scale*1.45,thumbOpen=this.dist(l[4],l[5])>scale*.58;return ext.every(Boolean)&&spread&&thumbOpen}
isFist(l){const scale=Math.max(.04,this.handScale),tips=[8,12,16,20],pips=[6,10,14,18],c=this.palmCenter(l);const curled=tips.map((t,i)=>this.curled(l,t,pips[i],.90));const compact=this.dist(l[8],l[20])<scale*1.05;const mean=tips.reduce((s,t)=>s+this.dist(l[t],c),0)/tips.length;return curled.every(Boolean)&&compact&&mean<scale*.92}
isScrollPose(l){const idx=this.extended(l,8,6,1.20),mid=this.extended(l,12,10,1.20),ring=this.extended(l,16,14,1.13),pink=this.extended(l,20,18,1.13),scale=Math.max(.04,this.handScale);return idx&&mid&&!ring&&!pink&&this.dist(l[8],l[12])>scale*.22}
isPointerPose(l){return this.extended(l,8,6,1.18)&&!this.extended(l,12,10,1.15)&&!this.extended(l,16,14,1.12)&&!this.extended(l,20,18,1.12)}
updateTracking(l){const raw=this.dist(l[0],l[9]);if(Number.isFinite(raw)&&raw>.03)this.handScale=this.handScale*.88+raw*.12;this.scaleFactor=this.clamp(this.handScale/this.refScale,.70,1.45);const ratio=this.handScale/this.refScale,quality=this.clamp(1-Math.abs(Math.log(ratio))/Math.log(2),0,1);let label='GOOD',hint='DISTANZA OK';if(this.handScale<.105){label='FAR';hint='AVVICINA LA MANO'}else if(this.handScale>.285){label='NEAR';hint='ALLONTANA LA MANO'}this.emit('tracking',{scale:this.handScale,factor:this.scaleFactor,quality,label,hint,adaptive:this.adaptiveScale,poseMotion:this.poseMotion});return{quality,label,hint}}
setIntent(type,confidence,data={}){confidence=this.clamp(confidence,0,1);if(type!==this.intent.type||Math.abs(confidence-this.intent.confidence)>.07){this.intent={type,confidence};this.stats.intents++;this.emit('intent',{type,confidence,...data})}}
clearIntent(){if(this.intent.type)this.emit('intent',{type:null,confidence:0});this.intent={type:null,confidence:0}}
disarm(){this.commandReady=false;this.restAt=0}
fire(type,data={},disarm=true){this.last=Date.now();this.clearIntent();if(disarm)this.disarm();this.stats.gestures++;this.stats[type]=(this.stats[type]||0)+1;this.emit('gesture',{type,...data,stats:{...this.stats}})}
updateNeutral({palm,fist,scrollPose,pinchNear,stable,now}){const neutral=!palm&&!fist&&!scrollPose&&!pinchNear;if(neutral&&stable){if(!this.restAt)this.restAt=now;if(now-this.restAt>=this.o.restHold)this.commandReady=true}else if(!neutral)this.restAt=0;const name=scrollPose?'scroll':palm?'palm':fist?'fist':pinchNear?'pinch':'neutral';if(name!==this.poseName){this.poseName=name;this.emit('pose',{name,armed:this.commandReady,stable,motion:this.poseMotion})}else this.emit('pose',{name,armed:this.commandReady,stable,motion:this.poseMotion});return neutral}
process(l){
this.stats.frames++;this.updateTracking(l);const now=Date.now(),idx=l[8],a=this.o.smooth;this.sx=this.sx*(1-a)+(1-idx.x)*a;this.sy=this.sy*(1-a)+idx.y*a;this.emit('pointer',{x:this.sx,y:this.sy});const motion=this.updatePoseMotion(l),stable=motion<this.o.poseStill,poseAllowed=now-this.last>this.o.safetyGap;
const sf=this.adaptiveScale?this.scaleFactor:1,pIn=this.o.pinchIn*sf,pOut=this.o.pinchOut*sf,d=this.dist(l[4],l[8]),pinchNear=d<pOut*1.03,palm=this.isPalm(l),fist=this.isFist(l),scrollPose=this.isScrollPose(l),pointerPose=this.isPointerPose(l),center=this.palmCenter(l);this.updateNeutral({palm,fist,scrollPose,pinchNear,stable,now});
if(scrollPose){if(!this.scrollAt){this.scrollAt=now;this.scrollLastY=center.y;this.scrollLastFire=now}const held=now-this.scrollAt;this.setIntent('scrollmode',held/this.o.scrollArm,{direction:'vertical'});if(held>=this.o.scrollArm){if(!this.scrollActive){this.scrollActive=true;this.emit('mode',{name:'scroll',active:true})}const dy=center.y-this.scrollLastY;if(Math.abs(dy)>=this.o.scrollStep&&now-this.scrollLastFire>120){this.fire('scroll',{direction:dy>0?'down':'up',delta:dy,mode:'two-finger'},false);this.scrollLastY=center.y;this.scrollLastFire=now}}return}else if(this.scrollActive||this.scrollAt){this.scrollActive=false;this.scrollAt=0;this.scrollLastY=null;this.emit('mode',{name:'scroll',active:false});if(this.intent.type==='scrollmode')this.clearIntent()}
if(fist){this.hist=[];this.pinchAt=0;if(this.commandReady&&stable&&poseAllowed&&this.fistArmed){if(!this.fistAt)this.fistAt=now;const held=now-this.fistAt;this.setIntent('fist',held/this.o.fistHold,{motion});if(held>=this.o.fistHold){this.fistArmed=false;this.fistAt=0;this.fire('fist',{deliberate:true,motion});return}}else{this.fistAt=0;if(this.intent.type==='fist')this.clearIntent()}return}else{this.fistAt=0;this.fistArmed=true}
if(palm){this.hist=[];this.pinchAt=0;if(this.commandReady&&stable&&poseAllowed&&this.palmArmed){if(!this.palmAt)this.palmAt=now;const held=now-this.palmAt;this.setIntent('palm',held/this.o.palmHold,{motion});if(held>=this.o.palmHold){this.palmArmed=false;this.palmAt=0;this.fire('palm',{deliberate:true,motion});return}}else{this.palmAt=0;if(this.intent.type==='palm')this.clearIntent()}return}else{this.palmAt=0;this.palmArmed=true}
if(d<pIn&&this.commandReady&&!this.pinch){if(!this.pinchAt)this.pinchAt=now;const held=now-this.pinchAt;this.setIntent('pinch',held/this.o.pinchHold,{x:this.sx,y:this.sy,adaptive:sf});if(held>=this.o.pinchHold&&now-this.last>this.o.cooldown){this.pinch=true;this.pinchAt=0;this.fire('pinch',{x:this.sx,y:this.sy,scaleFactor:sf})}}else if(d>pOut){this.pinch=false;this.pinchAt=0;if(this.intent.type==='pinch')this.clearIntent()}
if(pointerPose&&this.commandReady&&!this.pinch){this.hist.push({x:this.sx,y:this.sy,t:now});this.hist=this.hist.filter(p=>now-p.t<this.o.swipeWindow);if(this.hist.length>3){const first=this.hist[0],dx=this.sx-first.x,dy=this.sy-first.y,ax=Math.abs(dx),ay=Math.abs(dy);if(ax>.10&&ax>ay*2.2)this.setIntent('swipe',ax/this.o.swipeDistance,{direction:dx>0?'right':'left'});if(ax>=this.o.swipeDistance&&ax>ay*2.2&&now-this.last>this.o.cooldown){this.fire('swipe',{direction:dx>0?'right':'left',deliberate:true});this.hist=[]}}}else{this.hist=[];if(this.intent.type==='swipe')this.clearIntent()}
}
};