window.AirGestureEngine=class{
constructor(o={}){
this.profiles={
precise:{smooth:.20,pinchIn:.047,pinchOut:.078,swipeDistance:.26,swipeWindow:380,palmHold:1050,fistHold:1350,cooldown:760,poseStill:.010},
balanced:{smooth:.28,pinchIn:.052,pinchOut:.082,swipeDistance:.22,swipeWindow:340,palmHold:950,fistHold:1250,cooldown:650,poseStill:.012},
fast:{smooth:.38,pinchIn:.058,pinchOut:.09,swipeDistance:.18,swipeWindow:300,palmHold:850,fistHold:1150,cooldown:520,poseStill:.015}
};
this.profile=o.profile||'balanced';this.o={...this.profiles[this.profile],safetyGap:500,...o};this.adaptiveScale=o.adaptiveScale!==false;this.refScale=.18;this.handScale=this.refScale;this.scaleFactor=1;this.sx=.5;this.sy=.5;this.hist=[];this.pinch=false;this.palmAt=0;this.fistAt=0;this.palmArmed=true;this.fistArmed=true;this.last=0;this.listeners={};this.intent={type:null,confidence:0};this.poseMotion=0;this.lastPalmCenter=null;this.stats={frames:0,gestures:0,pinch:0,swipe:0,palm:0,scroll:0,fist:0,intents:0};
}
on(n,f){(this.listeners[n]??=[]).push(f);return this}
emit(n,d={}){(this.listeners[n]||[]).forEach(f=>f(d))}
setProfile(name){if(!this.profiles[name])return false;this.profile=name;Object.assign(this.o,this.profiles[name]);this.emit('profile',{name,options:{...this.o}});return true}
setAdaptiveScale(enabled){this.adaptiveScale=!!enabled;this.emit('adaptive',{enabled:this.adaptiveScale});return this.adaptiveScale}
dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
clamp(v,a,b){return Math.max(a,Math.min(b,v))}
palmCenter(l){const ids=[0,5,9,13,17];return{x:ids.reduce((s,i)=>s+l[i].x,0)/ids.length,y:ids.reduce((s,i)=>s+l[i].y,0)/ids.length}}
updatePoseMotion(l){const c=this.palmCenter(l);if(this.lastPalmCenter){const d=Math.hypot(c.x-this.lastPalmCenter.x,c.y-this.lastPalmCenter.y);this.poseMotion=this.poseMotion*.72+d*.28}this.lastPalmCenter=c;return this.poseMotion}
isPalm(l){const scale=Math.max(.04,this.handScale),tips=[8,12,16,20],pips=[6,10,14,18];const extended=tips.map((t,i)=>this.dist(l[t],l[0])>this.dist(l[pips[i]],l[0])*1.27);const spread=this.dist(l[8],l[20])>scale*1.28;const thumbOpen=this.dist(l[4],l[5])>scale*.46;return extended.every(Boolean)&&spread&&thumbOpen}
isFist(l){const scale=Math.max(.04,this.handScale),tips=[8,12,16,20],pips=[6,10,14,18];const curled=tips.map((t,i)=>this.dist(l[t],l[0])<this.dist(l[pips[i]],l[0])*.95&&this.dist(l[t],l[0])<scale*1.72);const compact=this.dist(l[8],l[20])<scale*1.35;return curled.filter(Boolean).length>=3&&curled[1]&&curled[2]&&compact}
updateTracking(l){const raw=this.dist(l[0],l[9]);if(Number.isFinite(raw)&&raw>.03)this.handScale=this.handScale*.88+raw*.12;this.scaleFactor=this.clamp(this.handScale/this.refScale,.70,1.45);const ratio=this.handScale/this.refScale,quality=this.clamp(1-Math.abs(Math.log(ratio))/Math.log(2),0,1);let label='GOOD',hint='DISTANZA OK';if(this.handScale<.105){label='FAR';hint='AVVICINA LA MANO'}else if(this.handScale>.285){label='NEAR';hint='ALLONTANA LA MANO'}this.emit('tracking',{scale:this.handScale,factor:this.scaleFactor,quality,label,hint,adaptive:this.adaptiveScale,poseMotion:this.poseMotion});return{quality,label,hint}}
setIntent(type,confidence,data={}){confidence=this.clamp(confidence,0,1);if(type!==this.intent.type||Math.abs(confidence-this.intent.confidence)>.08){this.intent={type,confidence};this.stats.intents++;this.emit('intent',{type,confidence,...data})}}
clearIntent(){if(this.intent.type)this.emit('intent',{type:null,confidence:0});this.intent={type:null,confidence:0}}
fire(type,data={}){this.last=Date.now();this.clearIntent();this.stats.gestures++;this.stats[type]=(this.stats[type]||0)+1;this.emit('gesture',{type,...data,stats:{...this.stats}})}
process(l){
this.stats.frames++;this.updateTracking(l);const now=Date.now(),idx=l[8],a=this.o.smooth;this.sx=this.sx*(1-a)+(1-idx.x)*a;this.sy=this.sy*(1-a)+idx.y*a;this.emit('pointer',{x:this.sx,y:this.sy});const motion=this.updatePoseMotion(l),stable=motion<this.o.poseStill,poseAllowed=now-this.last>this.o.safetyGap;
const fist=this.isFist(l);if(!fist){this.fistAt=0;this.fistArmed=true}else if(stable&&poseAllowed&&this.fistArmed){if(!this.fistAt)this.fistAt=now;const held=now-this.fistAt;this.setIntent('fist',held/this.o.fistHold,{motion});if(held>this.o.fistHold&&now-this.last>this.o.cooldown){this.fistArmed=false;this.fistAt=0;this.fire('fist',{deliberate:true,motion});return}return}else if(fist){this.fistAt=0;if(this.intent.type==='fist')this.clearIntent();return}
const palm=this.isPalm(l);if(!palm){this.palmAt=0;this.palmArmed=true}else if(stable&&poseAllowed&&this.palmArmed){if(!this.palmAt)this.palmAt=now;const held=now-this.palmAt;this.setIntent('palm',held/this.o.palmHold,{motion});if(held>this.o.palmHold&&now-this.last>this.o.cooldown){this.palmArmed=false;this.palmAt=0;this.fire('palm',{deliberate:true,motion});return}return}else if(palm){this.palmAt=0;if(this.intent.type==='palm')this.clearIntent()}
const sf=this.adaptiveScale?this.scaleFactor:1,pIn=this.o.pinchIn*sf,pOut=this.o.pinchOut*sf,d=this.dist(l[4],l[8]),pinchC=(pOut-d)/(pOut-pIn);if(!palm&&pinchC>.18&&!this.pinch)this.setIntent('pinch',pinchC,{x:this.sx,y:this.sy,adaptive:sf});if(d<pIn&&!this.pinch&&now-this.last>this.o.cooldown){this.pinch=true;this.fire('pinch',{x:this.sx,y:this.sy,scaleFactor:sf})}if(d>pOut)this.pinch=false;
this.hist.push({x:this.sx,y:this.sy,t:now});this.hist=this.hist.filter(p=>now-p.t<this.o.swipeWindow);if(this.hist.length>3){const first=this.hist[0],dx=this.sx-first.x,dy=this.sy-first.y,ax=Math.abs(dx),ay=Math.abs(dy);if(!palm&&!this.pinch&&ax>ay*1.25&&ax>.06)this.setIntent('swipe',ax/this.o.swipeDistance,{direction:dx>0?'right':'left'});else if(!palm&&!this.pinch&&ay>ax*1.25&&ay>.06)this.setIntent('scroll',ay/this.o.swipeDistance,{direction:dy>0?'down':'up'});else if(!palm&&!this.pinch&&ax<.04&&ay<.04&&this.intent.type&&['swipe','scroll'].includes(this.intent.type))this.clearIntent();if(now-this.last>this.o.cooldown){if(ax>this.o.swipeDistance&&ax>ay*1.25){this.fire('swipe',{direction:dx>0?'right':'left'});this.hist=[]}else if(ay>this.o.swipeDistance&&ay>ax*1.25){this.fire('scroll',{direction:dy>0?'down':'up',delta:dy});this.hist=[]}}}
}
};