(()=>{
const HISTORY_KEY='air_profile_memory',PROFILE_KEY='air_personal',HEALTH_KEY='air_profile_health',SESSION_KEY='air_profile_session_id';
const read=(k,store=localStorage)=>{try{return JSON.parse(store.getItem(k)||'null')}catch(e){return null}};
const write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch(e){return false}};
const sid=(()=>{let v=sessionStorage.getItem(SESSION_KEY);if(!v){v=Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8);sessionStorage.setItem(SESSION_KEY,v)}return v})();
let memory=read(HISTORY_KEY)||{profileStamp:0,entries:[]},lastFingerprint='';
const box=document.querySelector('#profileMemory'),name=document.querySelector('#memoryName'),bars=document.querySelector('#memoryBars'),hint=document.querySelector('#memoryHint'),meta=document.querySelector('#memoryMeta');
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function avg(a){return a.length?a.reduce((s,v)=>s+v,0)/a.length:0}
function snapshot(){const e=memory.entries||[],hs=e.map(x=>Number(x.health)||0),a=avg(hs),min=hs.length?Math.min(...hs):0,max=hs.length?Math.max(...hs):0,delta=hs.length>1?hs[hs.length-1]-hs[0]:0;let status='LEARNING';if(e.length>=2){if(a>=.78&&min>=.66)status='STABLE';else if(a>=.60&&min>=.45)status='WATCH';else status='REVIEW'}return{entries:e,count:e.length,avg:a,min,max,delta,status}}
function render(){if(!box)return;const s=snapshot();box.dataset.state=s.status;name.textContent=s.count?s.status:'EMPTY';hint.textContent=!s.count?'ATTENDI UNA SESSIONE VALIDATA':s.status==='STABLE'?'PROFILO STABILE NEL TEMPO':s.status==='WATCH'?'OSSERVA LE PROSSIME SESSIONI':s.status==='REVIEW'?'VALUTA NUOVA CALIBRAZIONE':'SERVE UNA SECONDA SESSIONE';meta.textContent=s.count?`${s.count} SESSION${s.count===1?'E':'I'} · MEDIA ${Math.round(s.avg*100)}%`:'NESSUNA MEMORIA';if(bars){bars.innerHTML='';const shown=s.entries.slice(-6);for(const e of shown){const i=document.createElement('i');i.style.height=Math.max(12,Math.round(clamp(e.health||0,0,1)*100))+'%';i.title=Math.round((e.health||0)*100)+'%';bars.appendChild(i)}for(let n=shown.length;n<6;n++){const i=document.createElement('i');i.className='empty';i.style.height='12%';bars.appendChild(i)}}}
function resetForProfile(stamp){memory={profileStamp:stamp||0,entries:[]};write(HISTORY_KEY,memory);lastFingerprint='';render()}
function sync(){const profile=read(PROFILE_KEY),health=read(HEALTH_KEY);if(!profile||!Number.isFinite(profile.createdAt)){if(memory.profileStamp!==0||memory.entries?.length)resetForProfile(0);else render();return}const stamp=profile.createdAt||0;if(memory.profileStamp!==stamp)resetForProfile(stamp);if(!health||health.profileStamp!==stamp||!Number.isFinite(health.health)||!health.updatedAt){render();return}const fp=[health.updatedAt,health.health,health.status,health.samples].join('|');if(fp===lastFingerprint){render();return}lastFingerprint=fp;let entry=(memory.entries||[]).find(e=>e.sessionId===sid);const data={sessionId:sid,health:clamp(health.health,0,1),status:health.status||'LEARNING',ratio:Number(health.ratio)||1,spread:Number(health.spread)||0,capRate:Number(health.capRate)||0,samples:Number(health.samples)||0,updatedAt:Number(health.updatedAt)||Date.now()};if(entry)Object.assign(entry,data);else (memory.entries??=[]).push({...data,startedAt:Date.now()});memory.entries=memory.entries.sort((a,b)=>(a.updatedAt||0)-(b.updatedAt||0)).slice(-8);write(HISTORY_KEY,memory);render()}
render();sync();setInterval(sync,2200);window.addEventListener('storage',e=>{if([PROFILE_KEY,HEALTH_KEY,HISTORY_KEY].includes(e.key)){memory=read(HISTORY_KEY)||memory;sync()}});
})();