window.AirProfileHealth=class{
constructor(profile=null){this.profile=null;this.ratios=[];this.factors=[];this.capHits=0;this.samples=0;this.setProfile(profile)}
clamp(v,a,b){return Math.max(a,Math.min(b,v))}
median(a){if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:(b[m-1]+b[m])/2}
setProfile(profile){this.profile=profile&&Number.isFinite(profile.refScale)?profile:null;this.ratios=[];this.factors=[];this.capHits=0;this.samples=0;return this.snapshot()}
tracking(q){if(!this.profile||!Number.isFinite(q?.scale))return;const ratio=q.scale/this.profile.refScale;if(!Number.isFinite(ratio)||ratio<.35||ratio>2.5)return;this.samples++;this.ratios.push(ratio);this.factors.push(Number.isFinite(q.factor)?q.factor:1);if(q.factor<=.705||q.factor>=1.445)this.capHits++;if(this.ratios.length>240)this.ratios.shift();if(this.factors.length>240)this.factors.shift();if(this.samples>240)this.capHits=Math.round(this.factors.filter(v=>v<=.705||v>=1.445).length)}
snapshot(){if(!this.profile)return{active:false,status:'OFF',health:0,samples:0,ratio:1,spread:0,capRate:0};const samples=this.ratios.length;if(!samples)return{active:true,status:'LEARNING',health:0,samples:0,ratio:1,spread:0,capRate:0};const ratio=this.median(this.ratios),dev=this.ratios.map(v=>Math.abs(v-ratio)),spread=this.median(dev),capRate=this.factors.length?this.factors.filter(v=>v<=.705||v>=1.445).length/this.factors.length:0,centerScore=1-this.clamp(Math.abs(ratio-1)/.55,0,1),consistencyScore=1-this.clamp(spread/.20,0,1),rangeScore=1-this.clamp(capRate/.35,0,1),health=this.clamp(centerScore*.35+consistencyScore*.35+rangeScore*.30,0,1);let status='LEARNING';if(samples>=45)status=health>=.78?'VALID':health>=.58?'ADAPT':'RECALIBRATE';return{active:true,status,health,samples,ratio,spread,capRate,refScale:this.profile.refScale,pinchFactor:this.profile.pinchFactor||1,createdAt:this.profile.createdAt||0}}
};
(()=>{if(typeof engine==='undefined')return;const PROFILE_KEY='air_personal',HEALTH_KEY='air_profile_health';const read=(k)=>{try{return JSON.parse(localStorage.getItem(k)||'null')}catch(e){return null}};let profile=read(PROFILE_KEY),saved=read(HEALTH_KEY),validator=new AirProfileHealth(profile),sessionCounted=false,lastSave=0;const box=document.querySelector('#profileHealth'),name=document.querySelector('#healthName'),bar=document.querySelector('#healthBar'),hint=document.querySelector('#healthHint'),meta=document.querySelector('#healthMeta'),personalLabel=document.querySelector('#personalLabel');function render(s,live=true){if(!box)return;if(!s.active){box.dataset.state='OFF';name.textContent='OFF';bar.style.width='0%';hint.textContent='CALIBRA PERSONAL';meta.textContent='SESSIONI —';return}const pc=Math.round(s.health*100),sessions=saved?.sessions||0;box.dataset.state=s.status;name.textContent=s.status==='LEARNING'?(live?'LEARNING':'LAST '+Math.round((saved?.health||0)*100)+'%'):s.status+' · '+pc+'%';bar.style.width=(s.status==='LEARNING'&&!live&&saved?Math.round(saved.health*100):pc)+'%';hint.textContent=s.status==='VALID'?'PROFILO COERENTE':s.status==='ADAPT'?'AUTOTUNE COMPENSA':s.status==='RECALIBRATE'?'CONSIGLIATA RICALIBRAZIONE':'RACCOLTA CAMPIONI';meta.textContent=`×${s.ratio.toFixed(2)} · ${sessions} SESSION${sessions===1?'E':'I'}`;if(personalLabel&&s.samples>=45)personalLabel.textContent=s.status==='VALID'?`Valido · ${pc}%`:s.status==='ADAPT'?`Adattato · ${pc}%`:`Ricalibra · ${pc}%`}
function persist(s){if(!s.active||s.samples<90)return;const stamp=s.createdAt||0;if(!saved||saved.profileStamp!==stamp){saved={sessions:0,profileStamp:stamp}}if(!sessionCounted){saved.sessions=(saved.sessions||0)+1;sessionCounted=true}const now=Date.now();if(now-lastSave<5000)return;lastSave=now;saved={...saved,health:s.health,status:s.status,ratio:s.ratio,spread:s.spread,capRate:s.capRate,samples:s.samples,updatedAt:now};localStorage.setItem(HEALTH_KEY,JSON.stringify(saved))}
if(profile){if(saved&&saved.profileStamp===(profile.createdAt||0)&&Number.isFinite(saved.health)){render({active:true,status:saved.status||'VALID',health:saved.health,samples:45,ratio:saved.ratio||1,spread:saved.spread||0,capRate:saved.capRate||0},false)}else render(validator.snapshot())}else render(validator.snapshot());engine.on('tracking',q=>{validator.tracking(q);const s=validator.snapshot();render(s,true);persist(s)}).on('calibration',()=>{profile=read(PROFILE_KEY);validator.setProfile(profile);sessionCounted=false;saved=null;localStorage.removeItem(HEALTH_KEY);render(validator.snapshot(),true)});})();